product更新機能追加
onituka/agile-project-management pull request #21
Opened 2021-11-21 15:08 UTC by kazumakawahara

# 概要
- product更新機能追加

2021-11-21 15:25 UTC, hryze requested changes
何点か指摘しました。

2021-11-21 15:25 UTC, hryze commented on pm/infrastructure/persistence/product.go
> +           FOR UPDATE`
インデントが崩れてます。
統一しましょう。

2021-11-21 15:25 UTC, hryze commented on pm/infrastructure/persistence/product.go
> +           id = ?`
ここもインデントが崩れてます。

2021-11-21 15:25 UTC, hryze commented on pm/infrastructure/persistence/product.go
> +              id = ?`
更新するカラムが足りてません。

2021-11-21 15:38 UTC, hryze requested changes

2021-11-21 15:38 UTC, hryze commented on pm/usecase/productusecse/product_input.go
> +	ID       string `json:"ID"`
product idは、request pathで受け取るのでjsonタグは必要ないです。

2021-11-21 15:54 UTC, kazumakawahara commented on pm/infrastructure/persistence/product.go
> +           FOR UPDATE`
ada31d3

インデントを修正しました。

2021-11-21 15:54 UTC, kazumakawahara commented on pm/infrastructure/persistence/product.go
> +           id = ?`
ada31d3

インデントを修正しました。

2021-11-22 00:15 UTC, revenue-hack commented on pm/usecase/productusecse/product.go
> +func (u *productUsecase) UpdateProduct(ctx context.Context, in *UpdateProductInput) (*UpdateProductOutput, error) {
これCreate,Updateなどユースケースを一緒の構造体のメソッドにするの辞めたほうが良いです。

凝集度が下がる、SRPに反するためです。

例えばDIしているRepositoryでCreateでは使うけどUpdateでは使わないといったものが出てくると、Update側でCreateのみで使うRepositoryがあり凝集度が下がる、また使わない予定のRepository使えてしまうなどのデメリットも発生します。

2021-11-22 02:11 UTC, hryze commented
@kazumakawahara 
コミットメッセージは具体的に書いてください。
こちらのコミットメッセージも間違えてるのでもうちょっと気を使ってコミットしましょう。

> fb8133e
インデックス修正

2021-11-22 05:17 UTC, kazumakawahara commented on pm/infrastructure/persistence/product.go
> +              id = ?`
e27470a

プロダクト更新時にプログラム側で更新日を生成するため更新sqlにupdated_atカラムを追加しました。

2021-11-22 06:05 UTC, kazumakawahara commented on pm/usecase/productusecse/product_input.go
> +	ID       string `json:"ID"`
d740829

プロダクト更新時リクエストパスパラメーターでproduct idを取得する為、UpdateProductInputのjsonタグを削除しました。

2021-11-23 06:49 UTC, kazumakawahara commented on pm/domain/productdm/product_domain_service.go
> +func (s *productDomainService) ExistsProductForUpdate(ctx context.Context, productDm *Product) (bool, error) {
作成時と更新時で処理内容は変わります。

どちらもプロダクトの存在を確認するものですが、明示的に作成時と更新時でロジックが異なりますので関数名を分けています。

2021-11-23 08:07 UTC, revenue-hack commented on pm/domain/productdm/product_domain_service.go
> +func (s *productDomainService) ExistsProductForUpdate(ctx context.Context, productDm *Product) (bool, error) {
なるほどです！了解しました！

2021-11-23 13:35 UTC, kazumakawahara commented on pm/usecase/productusecse/product.go
> +func (u *productUsecase) UpdateProduct(ctx context.Context, in *UpdateProductInput) (*UpdateProductOutput, error) {
dc84395

productのエンドポイントごとにusecase層の構造体を作成しました。

それに伴い、productのrouterを作成しました。
22448a3

またproduct用のmock生成ファイルも作成しました。
792ae86

2021-11-23 14:41 UTC, revenue-hack approved these changes

2021-11-23 15:01 UTC, merged