usecase層のCreateProjectテスト追加
onituka/agile-project-management pull request #22
Opened 2021-11-23 08:24 UTC by onituka

# 概要
usecase層のCreateProjectテスト追加

2021-11-23 11:53 UTC, hryze requested changes
何点かコメントしました。

2021-11-23 11:53 UTC, hryze commented on pm/usecase/projectusecse/project_test.go
> +			name:        "keyNameID不正",
ここのテストケース名のIDは不要です。

2021-11-23 11:53 UTC, hryze commented on pm/usecase/projectusecse/project_test.go
> +					KeyName:           "AAA",
ここのテストケースではKeyNameを不正な値にしないといけないです。

2021-11-23 11:53 UTC, hryze commented on pm/usecase/projectusecse/project_test.go
> +			name:        "nameID不正",
ここのテストケース名のIDは不要です。
テストケース名で何のテストをしているか一目で分かるよう、`プロダクト名不正`とした方が良いと思います。

2021-11-23 11:53 UTC, hryze commented on pm/usecase/projectusecse/project_test.go
> +					Name:              "管理ツール1",
ここのテストケースではNameを不正な値にしないといけないです。

2021-11-23 11:53 UTC, hryze commented on pm/usecase/projectusecse/project_test.go
> +					LeaderID:          "024d78d6-1d03-11ec-a478-0242ac184402",
ここのテストケースではLeaderIDを不正な値にしないといけないです。

2021-11-23 11:53 UTC, hryze commented on pm/usecase/projectusecse/project_test.go
> +					DefaultAssigneeID: "024d78d6-1d03-11ec-a478-9242ac180002",
ここのテストケースではDefaultAssigneeIDを不正な値にしないといけないです。

2021-11-23 11:53 UTC, hryze commented on pm/usecase/projectusecse/project.go
> +	defaultAssigneeIDVo, err := userdm.NewUserID(in.DefaultAssigneeID)
ここの修正はコミットを分けた方が良かったです。
やっていることが違うので。
今回はそのままでいきましょう。

2021-11-23 14:27 UTC, onituka commented on pm/usecase/projectusecse/project_test.go
> +			name:        "keyNameID不正",
baac365

修正しました。

2021-11-23 14:27 UTC, onituka commented on pm/usecase/projectusecse/project_test.go
> +					KeyName:           "AAA",
baac365

修正しました。

2021-11-23 14:32 UTC, onituka commented on pm/usecase/projectusecse/project_test.go
> +					Name:              "管理ツール1",
baac365

Nameの値を`AAA` → `A`へ修正。

2021-11-23 14:33 UTC, onituka commented on pm/usecase/projectusecse/project_test.go
> +					LeaderID:          "024d78d6-1d03-11ec-a478-0242ac184402",
baac365

LeaderIDの値を`024d78d6-1d03-11ec-a478-0242ac184402` → `invalid leader id`へ修正。

2021-11-23 14:35 UTC, onituka commented on pm/usecase/projectusecse/project_test.go
> +					DefaultAssigneeID: "024d78d6-1d03-11ec-a478-9242ac180002",
baac365

DefaultAssigneeIDの値を`024d78d6-1d03-11ec-a478-9242ac180002` → `invalid defaultAssignee id`へ修正。

2021-11-23 14:45 UTC, onituka commented on pm/usecase/projectusecse/project_test.go
> +			name:        "nameID不正",
ca0ca3d

テストケース名を`nameID不正` → `プロジェクト名不正` へ変更。

2021-11-23 15:02 UTC, hryze approved these changes

2021-11-24 02:15 UTC, revenue-hack approved these changes
実装は問題ないですが、project_test.goのファイル名だと汎用的で、他のファイルと名前がかぶり、実装の際のファイル検索時に探しづらいかと思うので、ファイル名は変えたほうが良いかなと思います。
project_usecase_test.go
とかにしてusecase層のテストだと言うことがわかると良いです。

2021-11-24 02:28 UTC, merged