CI追加
onituka/agile-project-management pull request #24
Opened 2021-11-26 04:35 UTC by kazumakawahara

# 概要
- CI追加

2021-11-26 04:45 UTC, revenue-hack submitted a review, later dismissed

2021-11-26 07:47 UTC, hryze requested changes

2021-11-26 07:47 UTC, hryze commented on .github/workflows/pm-test.yaml
> +# 共通処理
コメント削除してください。

2021-11-26 07:47 UTC, hryze commented on .github/workflows/pm-test.yaml
> +      # 処理を高速化するために環境をキャッシュ
ここもコメント削除してください。

2021-11-26 11:17 UTC, kazumakawahara commented on .github/workflows/pm-test.yaml
> +# 共通処理
f3778f2

コメント削除しました。

2021-11-26 11:17 UTC, kazumakawahara commented on .github/workflows/pm-test.yaml
> +      # 処理を高速化するために環境をキャッシュ
f3778f2

コメント削除しました。

2021-11-27 06:20 UTC, hryze requested changes

2021-11-27 06:20 UTC, hryze commented on .github/workflows/pm-test.yaml
> +          LOCAL_REDIS_DSN="127.0.0.1:6379" \
redis使ってないです。

2021-11-27 06:25 UTC, hryze requested changes

2021-11-27 06:25 UTC, hryze commented on .github/workflows/pm-test.yaml
> +      - uses: ./.github/.golangci.yaml
ここ記述の仕方がおかしいです。

2021-11-27 06:50 UTC, kazumakawahara commented on .github/workflows/pm-test.yaml
> +          LOCAL_REDIS_DSN="127.0.0.1:6379" \
34578d4
REDISを削除しました。

2021-11-27 09:12 UTC, hryze commented
https://github.com/nektos/actを使用してローカルで動作確認してください。

2021-11-27 14:48 UTC, kazumakawahara commented on .github/workflows/pm-test.yaml
> +      - uses: ./.github/.golangci.yaml
cc0127b

CIのRun golangci-lint jobを修正しました。

2021-11-27 14:50 UTC, hryze approved these changes

2021-11-27 15:04 UTC, hryze approved these changes
OKですー！

2021-11-27 15:05 UTC, merged