TrashedAtの時間生成のメソッド名変更
onituka/agile-project-management pull request #48
Opened 2021-12-21 08:33 UTC by onituka

## やったこと

TrashedAtの時間生成のメソッド名変更

## やらないこと

無し

## Request, Response 例

## 動作確認

・make run
・make lint

## その他

productの方でご指摘がありましたので、同じように修正しました。

2021-12-21 11:09 UTC, hryze requested changes
1点コメントしました。

2021-12-21 11:09 UTC, hryze commented on pm/domain/projectdm/project_model.go
>  	}
このメソッド内で現在時刻を生成してください。

2021-12-21 12:10 UTC, revenue-hack approved these changes
平さんのコメント以外特に問題ないです！

2021-12-21 23:12 UTC, hryze requested changes
コメントしましたー！

2021-12-21 23:12 UTC, hryze commented on pm/usecase/projectusecase/trashed_project_usecase.go
>  	now := u.timeManager.Now()
変数定義は、その変数を使用する直前で定義すると良いです。

2021-12-22 03:00 UTC, onituka commented on pm/usecase/projectusecase/trashed_project_usecase.go
>  	now := u.timeManager.Now()
95f781f

`createAt`,`updateAt`の生成処理を変更しました。
　・`createAt`の方はFactory側で生成するように変更
　・`updateAt`は`trashedAt`と同じようにドメインの`MoveToUpdate`のメソッド内で生成するよう変更

2022-01-04 15:13 UTC, onituka commented
19e2f52
・時間の生成をドメインモデルのメソッド内で生成するように変更したので、timemanagerを削除

31398d8
・上記修正に付随して、テストの時間のmock生成を修正

499b86b
・時間生成のメソッド名修正
　・`MoveToTrashed` → `MoveToTrashedAt` へ変更
　・`MoveToUpdated` → `ChangeUpdatedAt` へ変更

2022-01-04 15:17 UTC, hryze requested changes
1点コメントしました。

2022-01-04 15:17 UTC, hryze commented on pm/domain/projectdm/project_model.go
> +func (p *Project) MoveToTrashedAt() {
`MoveToTrashed`かな。
翻訳するとゴミ箱へ移動。

2022-01-04 15:29 UTC, onituka commented on pm/domain/projectdm/project_model.go
> +func (p *Project) MoveToTrashedAt() {
c6ed595
メソッド名を`MoveToTrashedAt` → `MoveToTrashed`へ変更

2022-01-04 16:07 UTC, hryze approved these changes
マージして大丈夫です！

2022-01-04 16:14 UTC, merged