productの検索機能追加
onituka/agile-project-management pull request #53
Opened 2022-01-14 04:58 UTC by kazumakawahara

## やったこと

- productの検索機能追加

## やらないこと

- 無し

## Request, Response 例

### Request
Method: GET
Path: /products/search/?name=プ&page=1&limit=50

<details>
<summary>Query Params(click):</summary>

```
- name
- page
- limit
```

</details>

### Response

<details>
<summary>body(click):</summary>

```
{
    "totalCount": 1,
    "products": [
        {
            "id": "4495c574-34c2-4fb3-9ca4-3a7c79c267a6",
            "groupID": "024d78d6-1d03-11ec-a478-0242ac180002",
            "name": "プロジェクト管理ツール",
            "leaderID": "4495c574-34c2-4fb3-9ca4-3a7c79c267a6",
            "createdAt": "2021-11-05T00:00:00Z",
            "updatedAt": "2021-11-05T00:00:00Z"
        }
    ]
}
```

</details>
-->

## 動作確認

- Postmanにて挙動確認
- make lint

2022-01-14 04:59 UTC, kazumakawahara commented
このPR内でテストも書いていきます。

2022-01-14 05:53 UTC, revenue-hack commented on pm/infrastructure/rdb/query/product_query_service_impl.go
> +func (r *productQueryServiceImpl) CountProductsByName(ctx context.Context, groupID string, name string) (totalCount int, err error) {
intではなくuint32など範囲を指定しましょう！

2022-01-14 05:53 UTC, revenue-hack commented on pm/interfaces/handler/producthandler/search_products_handler.go
> +		GroupID:     "024d78d6-1d03-11ec-a478-0242ac180002",
仮置きだと思うので、todoコメント入れておきましょうか

2022-01-14 05:53 UTC, revenue-hack commented on pm/usecase/productusecase/productoutput/search_products_output.go
> +	TotalCount int                    `json:"totalCount"`
範囲指定

2022-01-14 05:53 UTC, revenue-hack commented on pm/usecase/productusecase/search_products_usecase.go
> +	if in.Page <= 0 || in.Limit <= 0 || 50 < in.Limit {
あんまどうでも良いんですが、uintなので0未満になることはないですね

2022-01-14 06:12 UTC, kazumakawahara commented on pm/interfaces/handler/producthandler/search_products_handler.go
> +		GroupID:     "024d78d6-1d03-11ec-a478-0242ac180002",
4ad30dd
SearchProductsHandlerのGroupID指定に関するコメント追加

2022-01-14 06:26 UTC, kazumakawahara commented on pm/infrastructure/rdb/query/product_query_service_impl.go
> +func (r *productQueryServiceImpl) CountProductsByName(ctx context.Context, groupID string, name string) (totalCount int, err error) {
18a2c5e
totalCountの型をintからuint32に変更しました。

2022-01-14 06:27 UTC, kazumakawahara commented on pm/usecase/productusecase/productoutput/search_products_output.go
> +	TotalCount int                    `json:"totalCount"`
18a2c5e
totalCountの型をintからuint32に変更しました。

2022-01-14 06:40 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase.go
> +	if in.Page <= 0 || in.Limit <= 0 || 50 < in.Limit {
そうですね！
0にはなる可能性はある為、`val == 0`に変更するようにします！

合わせて、`fechproducts`の同一箇所も変更します！

2022-01-14 06:43 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase.go
> +	if in.Page <= 0 || in.Limit <= 0 || 50 < in.Limit {
da94513
searchproductsusecaseのpageとlimitのバリデーション変更

2022-01-14 08:00 UTC, revenue-hack submitted a review, later dismissed

2022-01-15 16:33 UTC, hryze requested changes
いくつかコメントしました。

2022-01-15 16:33 UTC, hryze commented on pm/usecase/productusecase/search_products_usecase_test.go
> +				ProductName := "プ"
`productName`ですね。

2022-01-15 16:33 UTC, hryze commented on pm/usecase/productusecase/search_products_usecase_test.go
> +				ProductName := "プ"
ここも`productName`です。

2022-01-15 16:33 UTC, hryze commented on pm/usecase/productusecase/search_products_usecase_test.go
> +				ProductName := "プ"
ここも`productName`です。

2022-01-15 16:33 UTC, hryze commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(10),
キャストは必要無いです。

2022-01-15 16:33 UTC, hryze commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(10),
ここもキャストは必要無いです。

2022-01-15 16:33 UTC, hryze commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(10),
ここもキャストは必要無いです。

2022-01-15 16:33 UTC, hryze commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(10),
ここもキャストは必要無いです。

2022-01-15 16:33 UTC, hryze commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(0),
ここもキャストは必要無いです。

2022-01-15 16:33 UTC, hryze commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(51),
ここもキャストは必要無いです。

2022-01-15 16:33 UTC, hryze commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(10),
ここもキャストは必要無いです。

2022-01-15 16:33 UTC, hryze commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(10),
ここもキャストは必要無いです。

2022-01-16 00:59 UTC, revenue-hack submitted a review, later dismissed

2022-01-16 01:00 UTC, revenue-hack commented
僕の方大丈夫ですー

2022-01-16 02:36 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase_test.go
> +				ProductName := "プ"
7b0371f
SearchProductsUsecaseテストのfield内のproductName名を変更しました。

2022-01-16 02:37 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase_test.go
> +				ProductName := "プ"
7b0371f
SearchProductsUsecaseテストのfield内のproductName名を変更しました。

2022-01-16 02:39 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase_test.go
> +				ProductName := "プ"
7b0371f
SearchProductsUsecaseテストのfield内のproductName名を変更しました。

2022-01-16 02:46 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(10),
c0f25e1
SearchProductsUsecaseテストInputのキャストを削除しました。

2022-01-16 02:46 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(10),
c0f25e1
SearchProductsUsecaseテストInputのキャストを削除しました。

2022-01-16 02:46 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(51),
c0f25e1
SearchProductsUsecaseテストInputのキャストを削除しました。

2022-01-16 02:46 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(0),
c0f25e1
SearchProductsUsecaseテストInputのキャストを削除しました。

2022-01-16 02:47 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(10),
c0f25e1
SearchProductsUsecaseテストInputのキャストを削除しました。

2022-01-16 02:47 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(10),
c0f25e1
SearchProductsUsecaseテストInputのキャストを削除しました。

2022-01-16 02:47 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(10),
c0f25e1
SearchProductsUsecaseテストInputのキャストを削除しました。

2022-01-16 02:47 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase_test.go
> +					Limit:       uint32(10),
c0f25e1
SearchProductsUsecaseテストInputのキャストを削除しました。

2022-01-16 02:57 UTC, hryze commented on pm/usecase/productusecase/search_products_usecase_test.go
> +				ProductName := "プ"
@kazumakawahara 
コミットメッセージは、「SearchProductsUsecaseテストの変数名を修正」の方が良いかな。

2022-01-16 02:58 UTC, hryze approved these changes
オッケーです！

2022-01-16 03:33 UTC, kazumakawahara commented on pm/usecase/productusecase/search_products_usecase_test.go
> +				ProductName := "プ"
了解！

2022-01-16 05:55 UTC, hryze approved these changes
オッケーです！

2022-01-16 15:03 UTC, merged