productnote更新機能追加
onituka/agile-project-management pull request #64
Opened 2022-01-18 19:32 UTC by kazumakawahara

## やったこと

- productnote更新機能追加

## やらないこと

- 無し

### Request
Method: PUT  
Path: /products/{productID}/notes/{productNoteID}

<details>
<summary>body(click):</summary>

```
{
    "title": "あああ",
    "content": " あああ",
    "createdBy": "039d71d6-1d03-11ec-a222-0242ac180002",
    "updatedBy": "128d71d6-1d03-11ec-a333-0242ac180002"
}
```

</details>

### Response

<details>
<summary>body(click):</summary>

```
{
    "id": "52dfc0d0-748e-11ec-88fd-acde48001122",
    "productID": "4495c574-34c2-4fb3-9ca4-3a7c79c267a6",
    "groupID": "024d78d6-1d03-11ec-a478-0242ac180002",
    "title": "あああ",
    "content": " あああ",
    "createdBy": "039d71d6-1d03-11ec-a222-0242ac180002",
    "updatedBy": "128d71d6-1d03-11ec-a333-0242ac180002",
    "createdAt": "2021-11-05T00:00:00Z",
    "updatedAt": "2022-01-18T19:28:57.428498Z"
}
```

</details>

## 動作確認

- postmanで動作確認
- make lint

## その他

- 同PR内でテスト書きます。

2022-01-19 01:48 UTC, revenue-hack commented on pm/usecase/productnoteusecase/update_product_note_usecase.go
> +	}
[ask] ここはプロダクトの存在確認をしているコードですか？

であればドメインサービス側に書いておくと良いです。

2022-01-19 08:49 UTC, kazumakawahara commented on pm/usecase/productnoteusecase/update_product_note_usecase.go
> +	}
@revenue-hack 
はい、プロダクトの存在確認をしているコードになります。
変更しましたので下記ご確認お願い致します。

4638b63
プロダクトの存在確認をドメインサービス経由に変更

2022-01-19 14:15 UTC, hryze requested changes
いくつかコメントしました。

2022-01-19 14:15 UTC, hryze commented on pm/infrastructure/rdb/persistence/product_note_repository_impl.go
> +
ここは改行いらないです。

2022-01-19 14:15 UTC, hryze commented on pm/infrastructure/rdb/persistence/product_note_repository_impl.go
> +
ここも改行いらないです。

2022-01-19 14:15 UTC, hryze commented on pm/usecase/productnoteusecase/update_product_note_usecase.go
> +	}
プロダクトノートの存在確認はdomain serviceに切り出した方が良さそうです。

2022-01-19 14:51 UTC, kazumakawahara commented on pm/infrastructure/rdb/persistence/product_note_repository_impl.go
> +
1f13973
不要な改行削除

2022-01-19 14:51 UTC, kazumakawahara commented on pm/infrastructure/rdb/persistence/product_note_repository_impl.go
> +
1f13973
不要な改行削除

2022-01-19 15:10 UTC, kazumakawahara commented on pm/usecase/productnoteusecase/update_product_note_usecase.go
> +	}
fe1e06f
プロダクトノートの存在確認をドメインサービス経由に変更

2022-01-19 15:39 UTC, hryze submitted a review, later dismissed
オッケーです！

2022-01-20 00:50 UTC, revenue-hack commented on pm/domain/productnotedm/product_note_domain_service.go
> +}
@kazumakawahara cc: @hryze 

すみません、ドメイン返したいと言うのはこういうことだったんですね。
https://architecture-studyhq.slack.com/archives/C02D3QCAEN5/p1642573894005600

であれば分けたほうが良いです。
理由は今回の場合、ドメイン取得したいのであれば、そのままリポジトリを呼ぶのと何ら変わらないかつ、関数名がExistsという名前だとドメインが返ってくるとは思わないからです。

なのでメソッドの中は
repositoryのerrチェックをしてboolを返すという処理になるかと思います。

2022-01-20 15:00 UTC, revenue-hack approved these changes

2022-01-20 15:00 UTC, merged