プロジェクトノート作成機能追加
onituka/agile-project-management pull request #75
Opened 2022-01-24 14:09 UTC by onituka

## やったこと

プロジェクトノート作成機能追加

## やらないこと

無し

## Request, Response 例

### Request
Method: POST 
Path: /products/4495c574-34c2-4fb3-9ca4-3a7c79c267a6/projects/024d71d6-1d03-11ec-a478-0242ac180002/notes

<details>
<summary>body(click):</summary>

```
{
  {
    "title": "プロジェクト開発まとめ",
    "content": "これからAAAaaa-123/-.",
    "CreatedBy": "039d71d6-1d03-11ec-a222-0242ac180002",
    "updatedBy": "128d71d6-1d03-11ec-a333-0242ac180002"
}
}
```

</details>

### Response

<details>
<summary>body(click):</summary>

```
{
    {
    "id": "d7d58bca-c440-4ee3-a1e8-519f3ba9a6fd",
    "productID": "4495c574-34c2-4fb3-9ca4-3a7c79c267a6",
    "projectID": "024d71d6-1d03-11ec-a478-0242ac180002",
    "groupID": "024d78d6-1d03-41ec-a478-0242ac180002",
    "title": "プロジェクト開発まとめ",
    "content": "これからAAAaaa-123/-.",
    "createdBy": "039d71d6-1d03-11ec-a222-0242ac180002",
    "updatedBy": "128d71d6-1d03-11ec-a333-0242ac180002",
    "createdAt": "2022-01-24T14:07:10.743516Z",
    "updatedAt": "2022-01-24T14:07:10.743516Z"
}
}
```

</details>

## 動作確認

・postmanにて挙動確認
・make run
・make lint

## その他

このプルリク内でテストも行います。

2022-01-24 15:00 UTC, hryze approved these changes
いくつかコメントしましたー！

2022-01-24 15:13 UTC, onituka commented on pm/domain/projectnotedm/project_note_domain_service.go
> +		return true, err
0bca2d5
ExistsProjectNoteForCreate関数の戻り値修正

2022-01-24 15:23 UTC, hryze requested changes
コメントしました。

2022-01-24 15:29 UTC, onituka commented on pm/domain/projectnotedm/project_note_repository.go
> +	FetchProjectNoteProjectIDAndTitle(ctx context.Context, projectID projectdm.ProjectID, title Title) (*ProjectNote, error)
69130a8
`FetchProjectNoteProjectIDAndTitle` → `FetchProjectNoteByProjectIDAndTitle` へ変更。

2022-01-24 16:26 UTC, onituka commented on pm/domain/projectnotedm/project_note_factory.go
> +}
d2ba37f
引数にuserIDを受け取り、createdByとupdateByにはめて渡すように修正。

2022-01-24 16:28 UTC, onituka commented on pm/interfaces/handler/projectnotehandler/create_project_note_handler.go
> +	}
d2ba37f

`GroupID`,`UserID`はJWT claimsに埋め込むため、暫定として決め打ちで受けとるように変更しました。

2022-01-24 16:29 UTC, onituka commented on pm/usecase/projectnoteusecase/projectnoteinput/create_project_note_input.go
> +	UpdatedBy string `json:"updatedBy"`
d2ba37f

ユーザーIDはJWT claimsに埋め込むため、jsonタグを削除しました。

2022-01-25 00:08 UTC, hryze approved these changes
おっけーです！

2022-01-25 01:12 UTC, revenue-hack commented on pm/domain/projectnotedm/project_note_content_vo.go
> +	if l := len(content); l == 0 || l > 65535 {
このcontentはおそらくマルチバイト(日本語など)も入ってくると思うので、`utf8.RuneCountInString`を使って長さを測ったほうが良いです！
lenだとバイト数が出てしまいます。

2022-01-25 01:12 UTC, revenue-hack commented on pm/infrastructure/rdb/persistence/project_note_repository_impl.go
> +	return projectNoteDm, nil
```suggestion
	return projectnotedm.Reconstruct(
		projectNoteDto.ID,
		projectNoteDto.ProductID,
		projectNoteDto.ProjectID,
		projectNoteDto.GroupID,
		projectNoteDto.Title,
		projectNoteDto.Content,
		projectNoteDto.CreatedBy,
		projectNoteDto.UpdatedBy,
		projectNoteDto.CreatedAt,
		projectNoteDto.UpdatedAt,
	)
	
```

2022-01-25 01:13 UTC, revenue-hack approved these changes
こちらも細かい指摘のみなので、LGTMです！

2022-01-25 10:16 UTC, onituka commented
2b12750
handler層のcreateProjectnoteテスト追加
d34c306
usecase層のcreateProjectnoteテスト追加

2022-01-25 10:19 UTC, onituka commented on pm/domain/projectnotedm/project_note_content_vo.go
> +	if l := len(content); l == 0 || l > 65535 {
contentの仕様としまして、text型のmax値の65535バイトまで許容するようにと考えています。
なのでバリデーションの時点でlenでバイト数で確認してするようにして、text型のmax値を超えるものは
エラーを返すようにしています。

2022-01-25 11:04 UTC, revenue-hack commented on pm/domain/projectnotedm/project_note_content_vo.go
> +	if l := len(content); l == 0 || l > 65535 {
なるほどです。

ただそれだとデータベースに引っ張られてドメイン知識が決まっているので、ドメインとして何文字かを設定したほうが良いです！

例えばposgreに変更したら1gまで可能なので、この値も変わってしまいます。

2022-01-25 11:36 UTC, onituka commented on pm/domain/projectnotedm/project_note_content_vo.go
> +	if l := len(content); l == 0 || l > 65535 {
確かにデータベースに依存していますね。
ドメインとして何文字か設定するように変更します！

2022-01-25 13:02 UTC, onituka commented on pm/infrastructure/rdb/persistence/project_note_repository_impl.go
> +	return projectNoteDm, nil
5206ba3
ご指摘の通り修正しました。

2022-01-25 13:04 UTC, onituka commented on pm/domain/projectnotedm/project_note_content_vo.go
> +	if l := len(content); l == 0 || l > 65535 {
d08ac66
0以上20000文字まで入るように設定しました。

2022-01-25 14:17 UTC, merged