プロジェクトノート更新機能追加
onituka/agile-project-management pull request #77
Opened 2022-01-26 04:08 UTC by onituka

## やったこと

プロジェクトノート更新機能追加

## やらないこと

無し

## Request, Response 例

### Request
Method: PUT 
Path: /products/4495c574-34c2-4fb3-9ca4-3a7c79c267a6/projects/024d71d6-1d03-11ec-a478-0242ac180002/notes/33b5db8f-f6c3-43bc-8e92-b8c3de50cc94
<details>
<summary>body(click):</summary>

```
{
   {
    "title": "テスト",
    "content": "テストです"
}
}
```

</details>

### Response

<details>
<summary>body(click):</summary>

```
{
   {
    "id": "33b5db8f-f6c3-43bc-8e92-b8c3de50cc94",
    "productID": "4495c574-34c2-4fb3-9ca4-3a7c79c267a6",
    "projectID": "024d71d6-1d03-11ec-a478-0242ac180002",
    "groupID": "024d78d6-1d03-41ec-a478-0242ac180002",
    "title": "テスト",
    "content": "テストです",
    "createdBy": "777d78d6-1d03-11ec-a478-0242ac184402",
    "updatedBy": "777d78d6-1d03-11ec-a478-0242ac184402",
    "createdAt": "2022-01-25T10:11:11Z",
    "updatedAt": "2022-01-25T10:11:11Z"
}
}
```

</details>

## 動作確認

・postmanにて挙動確認
・make run

## その他

テストもこのプルリク内で行います。

2022-01-29 05:07 UTC, hryze requested changes
1点コメントしましたー！

2022-01-29 05:07 UTC, hryze commented on pm/usecase/projectnoteusecase/update_project_note_usecase.go
> +	projectNoteDm.UpdatedAt()
ここは`projectNoteDm.ChangeUpdateAt()`ですかね。
ここは大関さんからのご指摘のように修正お願いします。
[#77 (comment)](https://github.com/onituka/agile-project-management/pull/77#discussion_r793262268)

2022-01-29 05:08 UTC, hryze commented
Request, Response例のjson形式がおかしい。
https://github.com/onituka/agile-project-management/pull/77#issue-1114607156

2022-01-29 09:22 UTC, onituka commented on pm/infrastructure/rdb/persistence/project_note_repository_impl.go
> +          updated_by = ?
5f5588f

更新が必要ですので修正しました。

2022-01-29 12:01 UTC, onituka commented on pm/domain/projectnotedm/project_model.go
> +}
598157c

更新者の変更メソッドが呼ばれるときに、更新日も更新されるように`ChangeUpdatedBy` のロジック修正

2022-01-30 10:23 UTC, onituka commented
0d09bf2
handler層のupdateProjectNoteテスト追加
3814617
usecase層のupdateProjectNoteテスト追加

2022-01-30 15:18 UTC, hryze reviewed
いくつかコメントしました。

2022-01-30 15:18 UTC, hryze commented on pm/domain/projectnotedm/project_model.go
> +	now := time.Now().UTC()
見やすさのために`p.updatedBy = updatedBy`と`now := time.Now().UTC()`の間に改行を入れた方が良さそうです。

2022-01-30 15:18 UTC, hryze commented on pm/interfaces/handler/projectnotehandler/update_project_note_handler.go
> +		UserID:    "777d78d6-1d03-11ec-a478-0242ac184402",
一時的な擬似データでもuuid v4の形式で入れてあげましょう。

2022-01-30 15:18 UTC, hryze commented on pm/interfaces/handler/projectnotehandler/update_project_note_handler_test.go
> +					"projectID":     "024d71d6-1d03-11ec-a478-0242ac180002",
テストデータもuuid v4の形式で入れてあげましょう。
テストを今後ドキュメントとしても活用するために。

2022-01-30 16:07 UTC, onituka commented on pm/domain/projectnotedm/project_model.go
> +	now := time.Now().UTC()
33013b2

修正しました。

2022-01-30 16:07 UTC, onituka commented on pm/interfaces/handler/projectnotehandler/update_project_note_handler_test.go
> +					"projectID":     "024d71d6-1d03-11ec-a478-0242ac180002",
8b2b332

v4形式に修正しました。

2022-01-30 16:07 UTC, onituka commented on pm/interfaces/handler/projectnotehandler/update_project_note_handler.go
> +		UserID:    "777d78d6-1d03-11ec-a478-0242ac184402",
8b2b332

v4形式に修正しました。

2022-01-31 08:42 UTC, hryze approved these changes
オッケーです！

2022-02-01 01:51 UTC, merged