productnote検索機能追加
onituka/agile-project-management pull request #78
Opened 2022-01-27 08:12 UTC by kazumakawahara

## やったこと

- productnote検索機能追加

## やらないこと

- 無し

## Request, Response 例

### Request
Method: GET  
Path: /products/{productID}/notes/search?title=ノ&page=1&limit=50

Query Params:

- page
- limit

### Response

<details>
<summary>body(click):</summary>

```
{
    "totalCount": 2,
    "productNotes": [
        {
            "id": "52dfc0d0-748e-41ec-88fd-acde48001122",
            "productID": "4495c574-34c2-4fb3-9ca4-3a7c79c267a6",
            "groupID": "024d78d6-1d03-41ec-a478-0242ac180002",
            "title": "ノート",
            "content": "note",
            "createdBy": "024d78d6-1d03-41ec-a478-0242ac184402",
            "updatedBy": "024d78d6-1d03-41ec-a478-0242ac184402",
            "createdAt": "2021-11-05T00:00:00Z",
            "updatedAt": "2021-11-05T00:00:00Z"
        },
        {
            "id": "62dfc0d0-748e-41ec-88fd-acde48001122",
            "productID": "4495c574-34c2-4fb3-9ca4-3a7c79c267a6",
            "groupID": "024d78d6-1d03-41ec-a478-0242ac180002",
            "title": "ノート2",
            "content": "test",
            "createdBy": "024d78d6-1d03-41ec-a478-0242ac184402",
            "updatedBy": "024d78d6-1d03-41ec-a478-0242ac184402",
            "createdAt": "2021-11-05T00:00:00Z",
            "updatedAt": "2021-11-05T00:00:00Z"
        }
    ]
}
```

</details>

## 動作確認

- Postmanにて挙動確認
- make lint
- make test
- make test update

## その他

- 同PR内でテストも書きます。

2022-01-29 04:34 UTC, revenue-hack submitted a review, later dismissed

2022-01-29 04:53 UTC, hryze requested changes
いくつかコメントしましたー！！

2022-01-29 04:53 UTC, hryze commented on pm/infrastructure/rdb/query/product_note_query_service_impl.go
> +func (r *productNoteQueryServiceImpl) SearchProductNotes(ctx context.Context, productID productdm.ProductID, title string, limit uint32, offset uint32) ([]*productnoteoutput.SearchProductNoteOutput,
引数で受け取っている`title`はプリミティブ型ではなく、value objectを受け取るようにしてください。

2022-01-29 04:53 UTC, hryze commented on pm/infrastructure/rdb/query/product_note_query_service_impl.go
> +func (r *productNoteQueryServiceImpl) CountProductNotesByTitle(ctx context.Context, productID productdm.ProductID, title string) (totalCount uint32, err error) {
ここも、引数で受け取っている`title`はプリミティブ型ではなく、value objectを受け取るようにしてください。

2022-01-29 04:53 UTC, hryze commented on pm/interfaces/handler/productnotehandler/search_product_notes_handler_test.go
> +							ID:        "52dfc0d0-748e-11ec-88fd-acde48001122",
テストデータとはいえ、実際に入るであろうデータを想定してはめるようにしてください。
今回のプロダクトでのuuid形式はv4を採用しています。
正規表現で表すと以下の形式です。
`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$`

テストコードはドキュメントとしても活用できるので、細かいですが正しいデータをはめるようにしてください。

2022-01-29 04:56 UTC, hryze commented
こちらの大関さんのご指摘も同プルリク内で取り入れましょう。
https://github.com/onituka/agile-project-management/pull/77#discussion_r793262268

2022-01-29 06:21 UTC, kazumakawahara commented on pm/infrastructure/rdb/query/product_note_query_service_impl.go
> +func (r *productNoteQueryServiceImpl) SearchProductNotes(ctx context.Context, productID productdm.ProductID, title string, limit uint32, offset uint32) ([]*productnoteoutput.SearchProductNoteOutput,
a7e81af
query_serviceで受け取るtitleの型をプリミティブ型からvalue objectに変更しました。

2022-01-29 06:22 UTC, kazumakawahara commented on pm/infrastructure/rdb/query/product_note_query_service_impl.go
> +func (r *productNoteQueryServiceImpl) CountProductNotesByTitle(ctx context.Context, productID productdm.ProductID, title string) (totalCount uint32, err error) {
a7e81af
query_serviceで受け取るtitleの型をプリミティブ型からvalue objectに変更しました。

2022-01-29 06:41 UTC, kazumakawahara commented on pm/interfaces/handler/productnotehandler/search_product_notes_handler_test.go
> +							ID:        "52dfc0d0-748e-11ec-88fd-acde48001122",
b5b6cd5
テストデータのuuid形式をv4の形式に変更しました。

2022-01-29 06:59 UTC, kazumakawahara commented
別PRで指摘されていた箇所の修正を実施。
#77 (comment)

5fe43f7
ドメインモデルのChangeUpdateAtメソッドをChangeUpdatedByメソッド内に含め、ChangeUpdateAtメソッドを削除

2022-01-29 10:25 UTC, revenue-hack commented on pm/domain/productnotedm/product_note_model.go
> +func (p *ProductNote) ChangeUpdatedByAndUpdateAt(updatedBy userdm.UserID) {
メソッド名はそのままで良いかなと思います。
UpdatedByを更新すること即ちupdatedatが更新されると言うのが自然なので。
敢えてDBに合わせる必要はないです(むしろDBに合わせないほうが良いです)。

2022-01-29 15:18 UTC, kazumakawahara commented on pm/domain/productnotedm/product_note_model.go
> +func (p *ProductNote) ChangeUpdatedByAndUpdateAt(updatedBy userdm.UserID) {
62b413c
ドメインモデルのメソッド名をChangeUpdatedByに変更しました。

2022-01-30 05:36 UTC, hryze reviewed
いくつか細かいとこ指摘しました！

2022-01-30 05:36 UTC, hryze commented on pm/usecase/productnoteusecase/search_product_notes_usecase_test.go
> +			name: "正常(検索にヒットしなかった場合)",
こちらのテストケースはいらないかなと思います。
`正常(プロダクトノートが存在しない場合)`と同じなので。

2022-01-30 05:36 UTC, hryze commented on pm/usecase/productnoteusecase/search_product_notes_usecase_test.go
> +					ProductID: "invalid product id",
routerの箇所でこの形式は事前に弾かれるはずです。
実際の不正なリクエストを想定して、16進数以外の値を入れる等で不正なデータをはめて欲しいです。

2022-01-30 05:36 UTC, hryze commented on pm/usecase/productnoteusecase/search_product_notes_usecase_test.go
> +			name:        "page値の不正",
テストケース名は詳細に書くといいです。
`クエリパラメータpage値の不正`みたいな感じです。
理由としてはテストコードをドキュメントとしても活用したいからです。

2022-01-30 06:21 UTC, kazumakawahara commented on pm/usecase/productnoteusecase/search_product_notes_usecase_test.go
> +			name: "正常(検索にヒットしなかった場合)",
dce73a6
usecase層のSearchProductNotesテストの重複テストケースを削除しました。

2022-01-30 06:24 UTC, kazumakawahara commented on pm/usecase/productnoteusecase/search_product_notes_usecase_test.go
> +					ProductID: "invalid product id",
2ccf166
usecase層のSearchProductNotesテストの不正な値を16進数以外の値に変更

2022-01-30 06:28 UTC, kazumakawahara commented on pm/usecase/productnoteusecase/search_product_notes_usecase_test.go
> +			name:        "page値の不正",
c4008be
usecase層のSearchProductNotesテストのテストケース名変更しました。

2022-01-30 06:28 UTC, kazumakawahara commented on pm/usecase/productnoteusecase/search_product_notes_usecase_test.go
> +					ProductID: "invalid product id",
その他テストに関しては次回以降のPRで修正します。

2022-01-30 07:22 UTC, hryze approved these changes
オッケーです！

2022-01-31 02:44 UTC, merged