プロジェクトノート検索機能追加
onituka/agile-project-management pull request #84
Opened 2022-02-03 11:06 UTC by onituka

## やったこと

プロジェクトノート検索機能追加

## やらないこと

無し

## Request, Response 例
### Request
Method: GET  
Path: /products/4487c574-34c2-4fb3-9ca4-3a7c79c267a6/projects/024d61d4-1d03-11ec-a478-0242ac180002/notes/search?title=プロジェクト&page=1&limit=50

<details>
<summary>QueryParams(click):</summary>

```
{
  titile プロジェクト
  page 1
  limit 50
}
```

</details>

### Response

<details>
<summary>body(click):</summary>

```
{
   "totalCount": 2,
    "projectNotes": [
        {
            "id": "112f23f8-2aaf-4261-b11c-709f24b4d200",
            "productID": "4487c574-34c2-4fb3-9ca4-3a7c79c267a6",
            "projectID": "024d61d4-1d03-11ec-a478-0242ac180002",
            "groupID": "024d78d6-1d03-41ec-a478-0242ac180002",
            "title": "プロジェクト開発まとめ",
            "content": "あいうえお",
            "createdBy": "777d78d6-1d03-11ec-a478-0242ac184402",
            "updatedBy": "777d78d6-1d03-11ec-a478-0242ac184402",
            "createdAt": "2022-02-01T07:29:04Z",
            "updatedAt": "2022-02-01T07:29:04Z"
        },
        {
            "id": "a512fafe-59e2-4c56-8367-3b77b5a5a32a",
            "productID": "4487c574-34c2-4fb3-9ca4-3a7c79c267a6",
            "projectID": "024d61d4-1d03-11ec-a478-0242ac180002",
            "groupID": "024d78d6-1d03-41ec-a478-0242ac180002",
            "title": "プロジェクト開発まとめ１",
            "content": "あいうえお",
            "createdBy": "777d78d6-1d03-11ec-a478-0242ac184402",
            "updatedBy": "777d78d6-1d03-11ec-a478-0242ac184402",
            "createdAt": "2022-02-01T07:29:11Z",
            "updatedAt": "2022-02-01T07:29:11Z"
        }
    ]
}
```

</details>

## 動作確認

postmanにて挙動確認
make run
make lint
make test

## その他

2022-02-03 11:33 UTC, revenue-hack commented on pm/usecase/projectnoteusecase/projectnoteinput/search_project_notes_input.go
> +	Title     string
[nits] そういえばstring系の検索は一応文字列制限を入れておくと良いです。
何文字でもOKにしてしまうと、思わぬバグを引き起こされる可能性があるため。
それかユースケース内でValueObjectに変換することで文字列制限をする形でも大丈夫です。

2022-02-03 11:50 UTC, onituka commented on pm/usecase/projectnoteusecase/projectnoteinput/search_project_notes_input.go
> +	Title     string
ユースケース内でValueObjectに変換する方で修正します！

2022-02-03 15:36 UTC, onituka commented on pm/usecase/projectnoteusecase/projectnoteinput/search_project_notes_input.go
> +	Title     string
[7efb4b9](https://github.com/onituka/agile-project-management/pull/84/commits/7efb4b910b91a8e971426004556b841229bd6343)

検索で入ってくるtitleをusecase内でValueObjectに変換するようにロジック修正。

2022-02-06 10:36 UTC, kazumakawahara approved these changes
👍

2022-02-06 12:06 UTC, revenue-hack submitted a review, later dismissed
LGTMです！

2022-02-13 05:52 UTC, hryze requested changes
コメントしました。

2022-02-13 05:52 UTC, hryze commented on pm/infrastructure/rdb/query/project_note_query_service_impl.go
> +		fmt.Sprintf("%%%s%%", title),
`title.Value()`でプリミティブ型の値を返すようにしてください。

2022-02-13 05:52 UTC, hryze commented on pm/infrastructure/rdb/query/project_note_query_service_impl.go
> +	if err = conn.QueryRowxContext(ctx, query, productID.Value(), projectID.Value(), fmt.Sprintf("%%%s%%", title)).Scan(&totalCount); err != nil {
ここも`title.Value()`でプリミティブ型の値を返すようにしてください。

2022-02-13 06:03 UTC, onituka commented on pm/infrastructure/rdb/query/project_note_query_service_impl.go
> +		fmt.Sprintf("%%%s%%", title),
[0f959c5](https://github.com/onituka/agile-project-management/pull/84/commits/0f959c52f0decda9a2205026c8f9178d7ad51963)
プリミティブ型で値を返すように修正。

2022-02-13 06:04 UTC, onituka commented on pm/infrastructure/rdb/query/project_note_query_service_impl.go
> +	if err = conn.QueryRowxContext(ctx, query, productID.Value(), projectID.Value(), fmt.Sprintf("%%%s%%", title)).Scan(&totalCount); err != nil {
[0f959c5](https://github.com/onituka/agile-project-management/pull/84/commits/0f959c52f0decda9a2205026c8f9178d7ad51963)
プリミティブ型で値を返すように修正。

2022-02-13 06:04 UTC, hryze approved these changes
オッケーです！

2022-02-13 06:05 UTC, merged